### ISSUE TITLE
Survey Service Client silently swallows any non-2XX response from rm-survey-service

### ISSUE THREAD

**Issue by HacktechLTD** [ONSdigital/rm-collection-exercise-service#86]
We are treating 404s (not found) the same as we are treating 5XX (internal server errors) and other errors which could be due to service being overloaded, not available, I/O problems etc. etc.

We shouldn't be returning null unless the HTTP response was definitely 404 from rm-survey-service.

We need to log anything that's unexpected (i.e. not 200 or 404) as it's going to cause problems... for example when we're creating CEs etc.

Code:
SurveySvcRestClientImpl.java - lines 142, 164 etc....

**Comment by damien-lloyd** [comment]
As this issue has been addressed with PR, this issue will now be closed. 

@NickGrantONS
